development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cubby
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rkarkut_cubby
  pool: 5
  username: rkarkut_cubby
  password: EOescBuI
  socket: /tmp/mysql.sock